name: test_coverage_badge
description: This package provides a CLI tool to generate and display test coverage badges for Dart projects.
version: 0.3.0
homepage: https://github.com/MohiuddinM/test_coverage_badge

environment:
  sdk: ^3.0.0

executables:
  test_coverage_badge:

dependencies:
  path: ^1.6.1
  glob: ^2.0.0
  args: ^2.5.0

dev_dependencies:
  test: ^1.16.7
